<?php

namespace AppBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends \Doctrine\ORM\EntityRepository
{
}
